# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: teambalancer_development

  username: rails_dev
  password: Qwerty1234
  host: localhost
  port: 5432

test:
  <<: *default
  database: teambalancer_test

  username: rails_dev
  password: Qwerty1234
  host: localhost
  port: 5432

production:
  <<: *default
  database: d7isdv18pov82t
  username: jlpeahvqnbkyby
  password: af1529f845751f90c28c213bd9b19fcd6851671deab8582b0214c2450f514ba5
